[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
cust = { path = "../crates/cust" }
kernels = { path = "kernels" }

[build-dependencies]
cuda_builder = { workspace = true, default-features = false }
